server:
  port: 8080
  servlet:
    context-path: /candidate-info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/candidateinfo
    username: candidate
    password: candidate
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    username: krishna.thota29@gmail.com
    password: Gmail@123
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

