server:
  servlet:
    context-path: /candidate-info
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/candidateinfo
    username: root
    password: root
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    username: krishna.thota29@gmail.com
    password: Gmail@123
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true